/**
 * Design system "Agro-Professional Utility" — AvicoleTrack
 * Généré à partir des maquettes Stitch (DESIGN.md)
 */

export const Colors = {
  surface: '#f9f9f9',
  surfaceDim: '#dadada',
  surfaceBright: '#f9f9f9',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f3f3f3',
  surfaceContainer: '#eeeeee',
  surfaceContainerHigh: '#e8e8e8',
  surfaceContainerHighest: '#e2e2e2',
  onSurface: '#1a1c1c',
  onSurfaceVariant: '#40493d',
  inverseSurface: '#2f3131',
  inverseOnSurface: '#f0f1f1',
  outline: '#707a6c',
  outlineVariant: '#bfcaba',
  surfaceTint: '#1b6d24',
  primary: '#0d631b',
  onPrimary: '#ffffff',
  primaryContainer: '#2e7d32',
  onPrimaryContainer: '#cbffc2',
  inversePrimary: '#88d982',
  secondary: '#7a5649',
  onSecondary: '#ffffff',
  secondaryContainer: '#fdcdbc',
  onSecondaryContainer: '#795548',
  tertiary: '#1f6223',
  onTertiary: '#ffffff',
  tertiaryContainer: '#3a7b39',
  onTertiaryContainer: '#c8ffbf',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  success: '#2e7d32',
  primaryFixed: '#a3f69c',
  primaryFixedDim: '#88d982',
  onPrimaryFixed: '#002204',
  onPrimaryFixedVariant: '#005312',
  secondaryFixed: '#ffdbcf',
  secondaryFixedDim: '#ebbcac',
  onSecondaryFixed: '#2e150b',
  onSecondaryFixedVariant: '#603f33',
  tertiaryFixed: '#acf4a4',
  tertiaryFixedDim: '#91d78a',
  onTertiaryFixed: '#002203',
  onTertiaryFixedVariant: '#0c5216',
  background: '#f9f9f9',
  onBackground: '#1a1c1c',
  surfaceVariant: '#e2e2e2',
  warning: '#d97706',
  slate: '#607D8B',
} as const;

export const darkThemePalette = {
  surface: '#1c2622',
  surfaceDim: '#18201d',
  surfaceBright: '#34433c',
  surfaceContainerLowest: '#202b26',
  surfaceContainerLow: '#27352f',
  surfaceContainer: '#2e3e36',
  surfaceContainerHigh: '#384a41',
  surfaceContainerHighest: '#43574c',
  onSurface: '#edf5ee',
  onSurfaceVariant: '#d8e9d6',
  inverseSurface: '#edf5ee',
  inverseOnSurface: '#111910',
  outline: '#a7b8aa',
  outlineVariant: '#425947',
  surfaceTint: '#9ee59b',
  primary: '#9ee59b',
  onPrimary: '#072d0c',
  primaryContainer: '#2d6f3a',
  onPrimaryContainer: '#dfffe0',
  inversePrimary: '#2c6935',
  secondary: '#f1c6aa',
  onSecondary: '#2b170d',
  secondaryContainer: '#7e5647',
  onSecondaryContainer: '#ffdcd0',
  tertiary: '#a0e99a',
  onTertiary: '#062d09',
  tertiaryContainer: '#397b3f',
  onTertiaryContainer: '#dcffd9',
  error: '#ffb4ab',
  onError: '#690005',
  errorContainer: '#93000a',
  onErrorContainer: '#ffdada',
  primaryFixed: '#d9ffd0',
  primaryFixedDim: '#9ee59b',
  onPrimaryFixed: '#08350f',
  onPrimaryFixedVariant: '#2d6f3a',
  secondaryFixed: '#ffdcd0',
  secondaryFixedDim: '#f1c6aa',
  onSecondaryFixed: '#2b170d',
  onSecondaryFixedVariant: '#7e5647',
  tertiaryFixed: '#dcffd9',
  tertiaryFixedDim: '#a0e99a',
  onTertiaryFixed: '#062d09',
  onTertiaryFixedVariant: '#397b3f',
  background: '#1a2420',
  onBackground: '#edf5ee',
  surfaceVariant: '#243427',
  warning: '#ffc267',
  slate: '#b4d1dc',
} as const;

export const Typography = {
  headlineLg: { fontSize: 32, fontWeight: '700' as const, lineHeight: 40, letterSpacing: -0.4 },
  headlineMd: { fontSize: 24, fontWeight: '600' as const, lineHeight: 32, letterSpacing: -0.2 },
  headlineMedium: { fontSize: 24, fontWeight: '600' as const, lineHeight: 32, letterSpacing: -0.2 },
  headlineLarge: { fontSize: 32, fontWeight: '700' as const, lineHeight: 40, letterSpacing: -0.4 },
  headlineSmall: { fontSize: 20, fontWeight: '600' as const, lineHeight: 28 },
  titleMedium: { fontSize: 18, fontWeight: '600' as const, lineHeight: 24 },
  titleLarge: { fontSize: 22, fontWeight: '700' as const, lineHeight: 28 },
  titleSmall: { fontSize: 16, fontWeight: '600' as const, lineHeight: 22 },
  bodyLg: { fontSize: 18, fontWeight: '400' as const, lineHeight: 28 },
  bodyLarge: { fontSize: 18, fontWeight: '400' as const, lineHeight: 28 },
  bodyMd: { fontSize: 16, fontWeight: '400' as const, lineHeight: 24 },
  bodyMedium: { fontSize: 16, fontWeight: '400' as const, lineHeight: 24 },
  bodySmall: { fontSize: 14, fontWeight: '400' as const, lineHeight: 20 },
  labelLg: { fontSize: 14, fontWeight: '600' as const, lineHeight: 20, letterSpacing: 0.5 },
  labelLarge: { fontSize: 14, fontWeight: '600' as const, lineHeight: 20, letterSpacing: 0.5 },
  labelMedium: { fontSize: 12, fontWeight: '600' as const, lineHeight: 18, letterSpacing: 0.4 },
  labelSmall: { fontSize: 11, fontWeight: '500' as const, lineHeight: 16, letterSpacing: 0.3 },
  displayMedium: { fontSize: 28, fontWeight: '700' as const, lineHeight: 36 },
  displaySmall: { fontSize: 24, fontWeight: '700' as const, lineHeight: 32 },
  displayLarge: { fontSize: 40, fontWeight: '800' as const, lineHeight: 48 },
  statDisplay: { fontSize: 40, fontWeight: '800' as const, lineHeight: 48 },
};

export const Radius = {
  xs: 4,
  sm: 4,
  DEFAULT: 8,
  md: 12,
  lg: 16,
  xl: 24,
  full: 9999,
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  touchTargetMin: 48,
  containerPadding: 20,
  stackGap: 16,
  gridGutter: 12,
};

export const Shadow = {
  card: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 3,
  },
  xs: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  sm: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 1,
  },
  lg: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 6,
  },
};
