-- Release-readiness fields for farm inventory and flock lifecycle.
ALTER TABLE farms
    ADD COLUMN IF NOT EXISTS food_type VARCHAR(100),
    ADD COLUMN IF NOT EXISTS food_quantity NUMERIC(12,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS food_unit VARCHAR(30) NOT NULL DEFAULT 'kg',
    ADD COLUMN IF NOT EXISTS water_quantity NUMERIC(12,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS water_unit VARCHAR(30) NOT NULL DEFAULT 'L';

ALTER TABLE flocks
    ADD COLUMN IF NOT EXISTS archived BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE farm_memberships
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_flocks_farm_active ON flocks(farm_id, archived);