"""initial_schema

Revision ID: 65469899cdf4
Revises: 
Create Date: 2026-09-03 20:45:19.680159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65469899cdf4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_deliveries_order'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('idx_orders_order_date'), table_name='orders')
    op.drop_index(op.f('idx_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.alter_column('conversation_members', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('conversation_members', 'conversation_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('conversation_members', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint(op.f('conversation_members_unique'), 'conversation_members', type_='unique')
    op.drop_index(op.f('idx_conversation_members_conversation'), table_name='conversation_members')
    op.drop_index(op.f('idx_conversation_members_user'), table_name='conversation_members')
    op.create_index(op.f('ix_conversation_members_conversation_id'), 'conversation_members', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_members_user_id'), 'conversation_members', ['user_id'], unique=False)
    op.drop_constraint(op.f('conversation_members_user_fk'), 'conversation_members', type_='foreignkey')
    op.drop_constraint(op.f('conversation_members_conversation_fk'), 'conversation_members', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'conversation_members', 'conversations', ['conversation_id'], ['id'])
    op.alter_column('conversations', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('conversations', 'enterprise_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('conversations', 'farm_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('conversations', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('idx_conversations_created'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_enterprise'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_farm'), table_name='conversations')
    op.create_index(op.f('ix_conversations_conversation_type'), 'conversations', ['conversation_type'], unique=False)
    op.create_index(op.f('ix_conversations_enterprise_id'), 'conversations', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_conversations_farm_id'), 'conversations', ['farm_id'], unique=False)
    op.drop_constraint(op.f('conversations_creator_fk'), 'conversations', type_='foreignkey')
    op.drop_constraint(op.f('conversations_enterprise_fk'), 'conversations', type_='foreignkey')
    op.drop_constraint(op.f('conversations_farm_fk'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'conversations', 'farms', ['farm_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'enterprises', ['enterprise_id'], ['id'])
    op.drop_constraint(op.f('conversations_type_check'), 'conversations', type_='check')
    op.alter_column('daily_reports', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('daily_reports', 'farm_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('daily_reports', 'flock_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('daily_reports', 'laying_percentage',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_reports', 'ratio',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('daily_reports', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('daily_reports', 'feed_used_bags',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_reports', 'water_used_liters',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_daily_reports_created_at'), table_name='daily_reports')
    op.drop_index(op.f('idx_daily_reports_created_by'), table_name='daily_reports')
    op.drop_index(op.f('idx_daily_reports_farm_date'), table_name='daily_reports')
    op.drop_index(op.f('idx_daily_reports_farm_flock_date'), table_name='daily_reports')
    op.drop_constraint(op.f('daily_reports_alveoli_check'), 'daily_reports', type_='check')
    op.drop_constraint(op.f('daily_reports_bird_count_check'), 'daily_reports', type_='check')
    op.drop_constraint(op.f('daily_reports_cartons_check'), 'daily_reports', type_='check')
    op.drop_constraint(op.f('daily_reports_eggs_check'), 'daily_reports', type_='check')
    op.drop_constraint(op.f('daily_reports_mortality_check'), 'daily_reports', type_='check')
    op.drop_constraint(op.f('daily_reports_remaining_check'), 'daily_reports', type_='check')
    op.drop_constraint(op.f('daily_reports_stock_check'), 'daily_reports', type_='check')
    op.drop_column('daily_reports', 'updated_at')
    op.alter_column('enterprises', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('enterprises', 'owner_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_enterprises_owner_id'), 'enterprises', ['owner_id'], unique=False)
    op.drop_constraint(op.f('enterprises_owner_fk'), 'enterprises', type_='foreignkey')
    op.create_foreign_key(None, 'enterprises', 'users', ['owner_id'], ['id'])
    op.alter_column('events', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('events', 'farm_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('events', 'flock_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('events', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('events', 'confirmed_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('idx_events_confirmed_at'), table_name='events')
    op.drop_index(op.f('idx_events_farm_date'), table_name='events')
    op.drop_index(op.f('idx_events_flock'), table_name='events')
    op.drop_index(op.f('idx_events_status'), table_name='events')
    op.create_index(op.f('ix_events_farm_id'), 'events', ['farm_id'], unique=False)
    op.create_index(op.f('ix_events_flock_id'), 'events', ['flock_id'], unique=False)
    op.drop_constraint(op.f('events_financial_amount_check'), 'events', type_='check')
    op.drop_constraint(op.f('events_financial_type_check'), 'events', type_='check')
    op.drop_constraint(op.f('events_status_check'), 'events', type_='check')
    op.drop_constraint(op.f('events_type_check'), 'events', type_='check')
    op.alter_column('farm_memberships', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text('\'{"create_event": false, "create_flock": false, "send_notification": false}\'::jsonb'))
    op.drop_index(op.f('idx_farm_memberships_farm_id'), table_name='farm_memberships')
    op.drop_index(op.f('idx_farm_memberships_user_id'), table_name='farm_memberships')
    op.drop_constraint(op.f('valid_membership_role'), 'farm_memberships', type_='check')
    op.alter_column('farms', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('farms', 'enterprise_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('idx_farms_enterprise_id'), table_name='farms')
    op.create_index(op.f('ix_farms_enterprise_id'), 'farms', ['enterprise_id'], unique=False)
    op.drop_constraint(op.f('farms_enterprise_fk'), 'farms', type_='foreignkey')
    op.create_foreign_key(None, 'farms', 'enterprises', ['enterprise_id'], ['id'])
    op.drop_constraint(op.f('farms_alveoli_check'), 'farms', type_='check')
    op.drop_constraint(op.f('farms_cartons_check'), 'farms', type_='check')
    op.drop_constraint(op.f('farms_food_quantity_check'), 'farms', type_='check')
    op.drop_constraint(op.f('farms_water_quantity_check'), 'farms', type_='check')
    op.alter_column('flock_race_presets', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('flock_race_presets', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_flock_race_presets'), table_name='flock_race_presets')
    op.alter_column('flocks', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('flocks', 'farm_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('idx_flocks_farm_active'), table_name='flocks')
    op.drop_constraint(op.f('flocks_bird_count_check'), 'flocks', type_='check')
    op.drop_column('flocks', 'created_at')
    op.alter_column('game_scores', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('game_scores', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('game_scores', 'difficulty_level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('idx_game_scores_game_type'), table_name='game_scores')
    op.drop_index(op.f('idx_game_scores_played'), table_name='game_scores')
    op.drop_index(op.f('idx_game_scores_played_at'), table_name='game_scores')
    op.drop_index(op.f('idx_game_scores_score_desc'), table_name='game_scores')
    op.drop_index(op.f('idx_game_scores_synced'), table_name='game_scores')
    op.drop_index(op.f('idx_game_scores_user'), table_name='game_scores')
    op.drop_index(op.f('idx_game_scores_user_game_type'), table_name='game_scores')
    op.create_index(op.f('ix_game_scores_game_type'), 'game_scores', ['game_type'], unique=False)
    op.create_index(op.f('ix_game_scores_synced'), 'game_scores', ['synced'], unique=False)
    op.create_index(op.f('ix_game_scores_user_id'), 'game_scores', ['user_id'], unique=False)
    op.drop_constraint(op.f('game_scores_user_fk'), 'game_scores', type_='foreignkey')
    op.create_foreign_key(None, 'game_scores', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('game_scores_score_check'), 'game_scores', type_='check')
    op.alter_column('invitations', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('invitations', 'enterprise_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('invitations', 'farm_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('invitations', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('idx_invitations_enterprise_id'), table_name='invitations')
    op.drop_index(op.f('idx_invitations_expires_at'), table_name='invitations')
    op.drop_index(op.f('idx_invitations_farm_id'), table_name='invitations')
    op.drop_index(op.f('idx_invitations_invited_email'), table_name='invitations')
    op.create_index(op.f('ix_invitations_enterprise_id'), 'invitations', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_invitations_expires_at'), 'invitations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_invitations_farm_id'), 'invitations', ['farm_id'], unique=False)
    op.create_index(op.f('ix_invitations_invited_email'), 'invitations', ['invited_email'], unique=False)
    op.drop_constraint(op.f('invitations_email_check'), 'invitations', type_='check')
    op.drop_constraint(op.f('invitations_role_check'), 'invitations', type_='check')
    op.alter_column('market_prices', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('market_prices', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('market_prices', 'price_low',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('market_prices', 'price_mid',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('market_prices', 'price_high',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('market_prices', 'note_low',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('market_prices', 'note_mid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('market_prices', 'note_high',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('market_prices', 'tags',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index(op.f('idx_market_prices_product_key_date'), table_name='market_prices')
    op.drop_index(op.f('idx_market_prices_region_date'), table_name='market_prices')
    op.create_index(op.f('ix_market_prices_product_key'), 'market_prices', ['product_key'], unique=False)
    op.drop_constraint(op.f('market_prices_price_check'), 'market_prices', type_='check')
    op.alter_column('messages', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('idx_messages_conversation'), table_name='messages')
    op.drop_index(op.f('idx_messages_created'), table_name='messages')
    op.drop_index(op.f('idx_messages_read'), table_name='messages')
    op.drop_index(op.f('idx_messages_sender'), table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.drop_constraint(op.f('messages_sender_fk'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_conversation_fk'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint(op.f('messages_type_check'), 'messages', type_='check')
    op.alter_column('notifications', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('notifications', 'event_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('idx_notifications_scheduled'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user'), table_name='notifications')
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('stock_movements', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('stock_movements', 'farm_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stock_movements', 'flock_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('stock_movements', 'created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('stock_movements', 'validated_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('stock_movements', 'market_price_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('idx_stock_movements_created_by'), table_name='stock_movements')
    op.drop_index(op.f('idx_stock_movements_farm_date'), table_name='stock_movements')
    op.drop_index(op.f('idx_stock_movements_flock'), table_name='stock_movements')
    op.drop_index(op.f('idx_stock_movements_type_date'), table_name='stock_movements')
    op.create_index(op.f('ix_stock_movements_created_by'), 'stock_movements', ['created_by'], unique=False)
    op.create_index(op.f('ix_stock_movements_farm_id'), 'stock_movements', ['farm_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_flock_id'), 'stock_movements', ['flock_id'], unique=False)
    op.drop_constraint(op.f('stock_movements_movement_type_check'), 'stock_movements', type_='check')
    op.drop_constraint(op.f('stock_movements_quantity_check'), 'stock_movements', type_='check')
    op.drop_constraint(op.f('stock_movements_status_check'), 'stock_movements', type_='check')
    op.drop_constraint(op.f('stock_movements_stock_type_check'), 'stock_movements', type_='check')
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(op.f('users_role_check'), 'users', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('users_role_check'), 'users', "role::text = ANY (ARRAY['OWNER'::character varying, 'MANAGER'::character varying, 'WORKER'::character varying]::text[])")
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_check_constraint(op.f('stock_movements_stock_type_check'), 'stock_movements', "stock_type::text = ANY (ARRAY['Aliments'::character varying, 'Œufs'::character varying, 'Cartons'::character varying, 'Alvéoles'::character varying, 'Sujets'::character varying, 'aliments'::character varying, 'oeufs'::character varying, 'cartons'::character varying, 'alveoles'::character varying, 'sujets'::character varying]::text[])")
    op.create_check_constraint(op.f('stock_movements_status_check'), 'stock_movements', "status::text = ANY (ARRAY['pending'::character varying, 'validated'::character varying, 'rejected'::character varying, 'cancelled'::character varying]::text[])")
    op.create_check_constraint(op.f('stock_movements_quantity_check'), 'stock_movements', 'quantity > 0::numeric')
    op.create_check_constraint(op.f('stock_movements_movement_type_check'), 'stock_movements', "movement_type::text = ANY (ARRAY['Entrée'::character varying, 'Sortie'::character varying]::text[])")
    op.drop_index(op.f('ix_stock_movements_flock_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_farm_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_created_by'), table_name='stock_movements')
    op.create_index(op.f('idx_stock_movements_type_date'), 'stock_movements', ['stock_type', sa.literal_column('movement_date DESC')], unique=False)
    op.create_index(op.f('idx_stock_movements_flock'), 'stock_movements', ['flock_id'], unique=False)
    op.create_index(op.f('idx_stock_movements_farm_date'), 'stock_movements', ['farm_id', sa.literal_column('movement_date DESC')], unique=False)
    op.create_index(op.f('idx_stock_movements_created_by'), 'stock_movements', ['created_by'], unique=False)
    op.alter_column('stock_movements', 'market_price_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_movements', 'validated_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_movements', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_movements', 'flock_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('stock_movements', 'farm_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('stock_movements', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.create_index(op.f('idx_notifications_user'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_scheduled'), 'notifications', ['scheduled_at'], unique=False)
    op.alter_column('notifications', 'event_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_check_constraint(op.f('messages_type_check'), 'messages', "message_type::text = ANY (ARRAY['TEXT'::character varying, 'ALERT'::character varying, 'NOTIFICATION'::character varying, 'SYSTEM'::character varying]::text[])")
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_fk'), 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messages_sender_fk'), 'messages', 'users', ['sender_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index(op.f('idx_messages_sender'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('idx_messages_read'), 'messages', ['conversation_id', 'read_at'], unique=False)
    op.create_index(op.f('idx_messages_created'), 'messages', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_messages_conversation'), 'messages', ['conversation_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_check_constraint(op.f('market_prices_price_check'), 'market_prices', 'price > 0::numeric')
    op.drop_index(op.f('ix_market_prices_product_key'), table_name='market_prices')
    op.create_index(op.f('idx_market_prices_region_date'), 'market_prices', ['region', sa.literal_column('price_date DESC')], unique=False)
    op.create_index(op.f('idx_market_prices_product_key_date'), 'market_prices', ['product_key', sa.literal_column('price_date DESC')], unique=False)
    op.alter_column('market_prices', 'tags',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('market_prices', 'note_high',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('market_prices', 'note_mid',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('market_prices', 'note_low',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('market_prices', 'price_high',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('market_prices', 'price_mid',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('market_prices', 'price_low',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('market_prices', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('market_prices', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_check_constraint(op.f('invitations_role_check'), 'invitations', "role::text = ANY (ARRAY['MANAGER'::character varying, 'WORKER'::character varying]::text[])")
    op.create_check_constraint(op.f('invitations_email_check'), 'invitations', 'length(TRIM(BOTH FROM invited_email)) > 0')
    op.drop_index(op.f('ix_invitations_invited_email'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_farm_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_expires_at'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_enterprise_id'), table_name='invitations')
    op.create_index(op.f('idx_invitations_invited_email'), 'invitations', ['invited_email'], unique=False)
    op.create_index(op.f('idx_invitations_farm_id'), 'invitations', ['farm_id'], unique=False)
    op.create_index(op.f('idx_invitations_expires_at'), 'invitations', ['expires_at'], unique=False)
    op.create_index(op.f('idx_invitations_enterprise_id'), 'invitations', ['enterprise_id'], unique=False)
    op.alter_column('invitations', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('invitations', 'farm_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('invitations', 'enterprise_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('invitations', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_check_constraint(op.f('game_scores_score_check'), 'game_scores', 'score >= 0')
    op.drop_constraint(None, 'game_scores', type_='foreignkey')
    op.create_foreign_key(op.f('game_scores_user_fk'), 'game_scores', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_game_scores_user_id'), table_name='game_scores')
    op.drop_index(op.f('ix_game_scores_synced'), table_name='game_scores')
    op.drop_index(op.f('ix_game_scores_game_type'), table_name='game_scores')
    op.create_index(op.f('idx_game_scores_user_game_type'), 'game_scores', ['user_id', 'game_type'], unique=False)
    op.create_index(op.f('idx_game_scores_user'), 'game_scores', ['user_id'], unique=False)
    op.create_index(op.f('idx_game_scores_synced'), 'game_scores', ['synced'], unique=False)
    op.create_index(op.f('idx_game_scores_score_desc'), 'game_scores', [sa.literal_column('score DESC')], unique=False)
    op.create_index(op.f('idx_game_scores_played_at'), 'game_scores', [sa.literal_column('played_at DESC')], unique=False)
    op.create_index(op.f('idx_game_scores_played'), 'game_scores', [sa.literal_column('played_at DESC')], unique=False)
    op.create_index(op.f('idx_game_scores_game_type'), 'game_scores', ['game_type'], unique=False)
    op.alter_column('game_scores', 'difficulty_level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('game_scores', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('game_scores', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('flocks', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.create_check_constraint(op.f('flocks_bird_count_check'), 'flocks', 'bird_count >= 0')
    op.create_index(op.f('idx_flocks_farm_active'), 'flocks', ['farm_id', 'archived'], unique=False)
    op.alter_column('flocks', 'farm_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('flocks', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('idx_flock_race_presets'), 'flock_race_presets', ['category'], unique=False)
    op.alter_column('flock_race_presets', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('flock_race_presets', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_check_constraint(op.f('farms_water_quantity_check'), 'farms', 'water_quantity >= 0::numeric')
    op.create_check_constraint(op.f('farms_food_quantity_check'), 'farms', 'food_quantity >= 0::numeric')
    op.create_check_constraint(op.f('farms_cartons_check'), 'farms', 'cartons >= 0')
    op.create_check_constraint(op.f('farms_alveoli_check'), 'farms', 'alveoli >= 0 AND alveoli < 12')
    op.drop_constraint(None, 'farms', type_='foreignkey')
    op.create_foreign_key(op.f('farms_enterprise_fk'), 'farms', 'enterprises', ['enterprise_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_farms_enterprise_id'), table_name='farms')
    op.create_index(op.f('idx_farms_enterprise_id'), 'farms', ['enterprise_id'], unique=False)
    op.alter_column('farms', 'enterprise_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('farms', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_check_constraint(op.f('valid_membership_role'), 'farm_memberships', "role::text = ANY (ARRAY['OWNER'::character varying, 'MANAGER'::character varying, 'WORKER'::character varying]::text[])")
    op.create_index(op.f('idx_farm_memberships_user_id'), 'farm_memberships', ['user_id'], unique=False)
    op.create_index(op.f('idx_farm_memberships_farm_id'), 'farm_memberships', ['farm_id'], unique=False)
    op.alter_column('farm_memberships', 'permissions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text('\'{"create_event": false, "create_flock": false, "send_notification": false}\'::jsonb'))
    op.create_check_constraint(op.f('events_type_check'), 'events', "type::text = ANY (ARRAY['vaccination'::character varying, 'treatment'::character varying, 'reform'::character varying, 'breeding'::character varying, 'inspection'::character varying, 'other'::character varying]::text[])")
    op.create_check_constraint(op.f('events_status_check'), 'events', "status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'rejected'::character varying, 'cancelled'::character varying]::text[])")
    op.create_check_constraint(op.f('events_financial_type_check'), 'events', "financial_type IS NULL OR (financial_type::text = ANY (ARRAY['cost'::character varying, 'benefit'::character varying]::text[]))")
    op.create_check_constraint(op.f('events_financial_amount_check'), 'events', 'financial_amount IS NULL OR financial_amount >= 0::numeric')
    op.drop_index(op.f('ix_events_flock_id'), table_name='events')
    op.drop_index(op.f('ix_events_farm_id'), table_name='events')
    op.create_index(op.f('idx_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('idx_events_flock'), 'events', ['flock_id'], unique=False)
    op.create_index(op.f('idx_events_farm_date'), 'events', ['farm_id', 'event_date'], unique=False)
    op.create_index(op.f('idx_events_confirmed_at'), 'events', ['confirmed_at'], unique=False)
    op.alter_column('events', 'confirmed_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('events', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('events', 'flock_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('events', 'farm_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('events', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'enterprises', type_='foreignkey')
    op.create_foreign_key(op.f('enterprises_owner_fk'), 'enterprises', 'users', ['owner_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_enterprises_owner_id'), table_name='enterprises')
    op.alter_column('enterprises', 'owner_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('enterprises', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('daily_reports', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.create_check_constraint(op.f('daily_reports_stock_check'), 'daily_reports', 'egg_stock >= 0')
    op.create_check_constraint(op.f('daily_reports_remaining_check'), 'daily_reports', 'remaining_eggs >= 0')
    op.create_check_constraint(op.f('daily_reports_mortality_check'), 'daily_reports', 'mortality >= 0')
    op.create_check_constraint(op.f('daily_reports_eggs_check'), 'daily_reports', 'eggs_produced >= 0')
    op.create_check_constraint(op.f('daily_reports_cartons_check'), 'daily_reports', 'cartons >= 0')
    op.create_check_constraint(op.f('daily_reports_bird_count_check'), 'daily_reports', 'bird_count >= 0')
    op.create_check_constraint(op.f('daily_reports_alveoli_check'), 'daily_reports', 'alveoli >= 0')
    op.create_index(op.f('idx_daily_reports_farm_flock_date'), 'daily_reports', ['farm_id', 'flock_id', 'report_date'], unique=False)
    op.create_index(op.f('idx_daily_reports_farm_date'), 'daily_reports', ['farm_id', 'report_date'], unique=False)
    op.create_index(op.f('idx_daily_reports_created_by'), 'daily_reports', ['created_by'], unique=False)
    op.create_index(op.f('idx_daily_reports_created_at'), 'daily_reports', ['created_at'], unique=False)
    op.alter_column('daily_reports', 'water_used_liters',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_reports', 'feed_used_bags',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_reports', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('daily_reports', 'ratio',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('daily_reports', 'laying_percentage',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('daily_reports', 'flock_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('daily_reports', 'farm_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('daily_reports', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_check_constraint(op.f('conversations_type_check'), 'conversations', "conversation_type::text = ANY (ARRAY['DIRECT'::character varying, 'GROUP'::character varying, 'FARM'::character varying, 'ENTERPRISE'::character varying]::text[])")
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_farm_fk'), 'conversations', 'farms', ['farm_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('conversations_enterprise_fk'), 'conversations', 'enterprises', ['enterprise_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('conversations_creator_fk'), 'conversations', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_conversations_farm_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_enterprise_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_conversation_type'), table_name='conversations')
    op.create_index(op.f('idx_conversations_farm'), 'conversations', ['farm_id'], unique=False)
    op.create_index(op.f('idx_conversations_enterprise'), 'conversations', ['enterprise_id'], unique=False)
    op.create_index(op.f('idx_conversations_created'), 'conversations', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('conversations', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('conversations', 'farm_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('conversations', 'enterprise_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'conversation_members', type_='foreignkey')
    op.drop_constraint(None, 'conversation_members', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_members_conversation_fk'), 'conversation_members', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('conversation_members_user_fk'), 'conversation_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversation_members_user_id'), table_name='conversation_members')
    op.drop_index(op.f('ix_conversation_members_conversation_id'), table_name='conversation_members')
    op.create_index(op.f('idx_conversation_members_user'), 'conversation_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_conversation_members_conversation'), 'conversation_members', ['conversation_id'], unique=False)
    op.create_unique_constraint(op.f('conversation_members_unique'), 'conversation_members', ['conversation_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('conversation_members', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('conversation_members', 'conversation_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('conversation_members', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('orders',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('order_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('product', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'partially_delivered'::character varying, 'delivered'::character varying, 'cancelled'::character varying]::text[])", name=op.f('orders_status_check')),
    sa.CheckConstraint('quantity >= 0', name=op.f('orders_quantity_check')),
    sa.CheckConstraint('total_amount >= 0::numeric', name=op.f('orders_total_check')),
    sa.CheckConstraint('unit_price >= 0::numeric', name=op.f('orders_unit_price_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    op.create_index(op.f('idx_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('idx_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('delivery_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'in_transit'::character varying, 'delivered'::character varying, 'cancelled'::character varying]::text[])", name=op.f('deliveries_status_check')),
    sa.CheckConstraint('quantity >= 0', name=op.f('deliveries_quantity_check')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('deliveries_order_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('deliveries_pkey'))
    )
    op.create_index(op.f('idx_deliveries_order'), 'deliveries', ['order_id'], unique=False)
    # ### end Alembic commands ###
